### ISSUE TITLE
Issue in following along the embassy-rs setup tutorial

### ISSUE THREAD

**Issue by UdrAlberto** [UPB-FILS-MA/questions#1]
Good evening!
While following through the embassy-rs setup tutorial, after running the command `cargo install elf2uf2-rs`, I encountered the following error:

![image](https://github.com/UPB-FILS-MA/questions/assets/94986973/93aa2dc5-2b93-4267-9e4b-66faa76256bb)

It was easily solved by installing a missing dependency, the package libudev, by running the command `sudo apt-get install -y  libudev-dev`, however I believe this should also be mentioned in the tutorial, in the Prerequisites section.

Thanks!

**Comment by alexandruradovici** [comment]
Thank you for pointing out this. Could you please use the *Edit this page* function at tge bottom of the tutorial, edit the Linux section of the page by adding a info section (:::info ... :::) and send us a pull request?

**Comment by UdrAlberto** [comment]
Done, thanks for the support!
