### ISSUE TITLE
[Pitch Detector] - Microphone Filters

### ISSUE THREAD

**Issue by aleqbee** [UPB-FILS-MA/questions#11]
# Question

## Question
For my "Pitch Detection" project I want to use the Ky-038 microphone module, but I am not sure if I should also use a high-pass filter or it's no longer necessary since this module has a potentiometer. 

If yes, what filter should I use, because I cannot find anything.

Link to the mic module: https://www.bitmi.ro/modul-senzor-sunet-cu-microfon-ky-038-10658.html?gad_source=1&gclid=CjwKCAjw_e2wBhAEEiwAyFFFo7CE-VVMXSu2j_fgrPENW_PS-eBF6gUa8oD-zfGMlTezQpGQoTeNkhoC1BIQAvD_BwE

## Details
- Link to your project repository:

https://github.com/UPB-FILS-MA/project-aleqbee

**Comment by irina-b-dev** [comment]
@aleqbee I tried to look into the your project description. But I am not sure I understand your question. 
I don't know if you would need any filter. The range of the input signal won't be larger if you add a high-pass filter (it will only let high frequency audio pass). The potentiometer will only shift the range of the input signal. 
Also keep in mind that the links you attached in the README contain only code written for Intel or AMD x86-64 etc processors. To detect frequencies you will probably need to implement FFT (Fast Fourier Transform) in Rust or find a crate for embedded that implements it. After a quick search I have found  two creates : [fixed-fft](https://crates.io/crates/fixed-fft) and [microfft](https://crates.io/crates/microfft), but I am not sure if they are going to work in work in your case.
