### ISSUE TITLE
[lab] lab7 solution doesn't seems to work

### ISSUE THREAD

**Issue by U-alb** [UPB-FILS-MA/questions#13]
# Nonfunctional lab7 code

## Details

Could you please check what seems to be the issue? My first hypothesis was a kernel panic, but after debugging with some match() structures, I've noticed that the program seems to stop inside an embassy function, so my hypothesis is highly unplausible.

- Link in the lab: https://github.com/UPB-FILS-MA/lab/blob/main/lab07/lab07_all/src/main.rs
- Link to our code: https://github.com/UPB-FILS-MA/lab-UdrAlberto/tree/main/lab07/lab07_all/src/main.rs

We've also checked the lab solution (https://github.com/UPB-FILS-MA/lab-solutions/blob/main/lab07/lab07_all/src/bin/solution.rs) but couldn't find out what went wrong.

**Comment by TeodoraMiu** [comment]
You are not reading and writing the values from the sensor correctly. The first parameter of the `read` and `write` functions for I2C is supposed to be the I2C address of the sensor, not the address of the register. The address of the register is stored in the TX buffer, that is then sent to the sensor.
Look carefully at how the `read` and `write` functions are being used in the lab solutions.

**Comment by U-alb** [comment]
Thanks!
