### ISSUE TITLE
Path too long for compiling

### ISSUE THREAD

**Issue by cristianaprecup** [UPB-FILS-MA/questions#17]
## Question
When I'm trying to cargo build i get this error that tells me that my compiling path is too long. I tried to move it on C:/ drive so that I shorten the path, and also to enable long path support in Windows but I didn't succeed to build it. What should I do?

![image](https://github.com/UPB-FILS-MA/questions/assets/121363102/d9e197ce-f368-42e9-a991-7c785985f826)

## Details
I got this error after installing the crate for controlling servo motors: https://crates.io/crates/esp-idf-servo

**Comment by cristianaprecup** [comment]
I managed to add my project in a Linux environment and I got the following error, this crate is not compatible with thumbv6m-none-eabi:  
![image](https://github.com/UPB-FILS-MA/questions/assets/121363102/fe215082-03fa-495a-bd01-22a81bb7c41a)
I couldn't find any other useful crate for controlling the SG90 micro servo motor that I am using, do you know any? Thank you.

**Comment by alexandruradovici** [comment]
You cannot use the ESP crates as ESP is a RISC-V and not ARM processor. It also uses the ESP-IDF library which is not available on the Raspberry Pici.

The servo should be controlled by a simole PWM which you can actually write.

Here you have an example for the microbit https://alelouis.eu/blog/pwm-microbit/. The API is a little different, but take into account just the PWM parameters and adapt them for your code.

This https://github.com/paunstefan/sg90_pi is a crate for the big Raspberry Pi, you can adapt the code for the Pico by exchanging tge used PWM API with the Pico's embassy PWM API.

**Comment by alexandruradovici** [comment]
Is this solved?

**Comment by cristianaprecup** [comment]
Yes, I managed to solve it.
