### ISSUE TITLE
Problem with libraries for project

### ISSUE THREAD

**Issue by Angery-Stoman** [UPB-FILS-MA/questions#18]
Rust is giving me this error because of a library in embassy:
can't find crate for `std`
the `thumbv6m-none-eabi` target may not support the standard library
`std` is required by `embassy` because it does not declare `#![no_std]`

**Comment by alexandruradovici** [comment]
The embassy crate is `no_std`, can you please be more specific with the error? A screenshot maybe.

**Comment by Angery-Stoman** [comment]
I tried using cargo build again and the error completely changed.
My lib.rs is currently empty.
<img width="673" alt="image" src="https://github.com/UPB-FILS-MA/questions/assets/163386844/b1141064-492f-46df-a0a8-ffcf7cbd606a">
These are the libraries that I am currently using and where the problem seems to stem from.
<img width="494" alt="image" src="https://github.com/UPB-FILS-MA/questions/assets/163386844/e7fc9cff-27ee-4479-96ca-200c10a8f5a6">

**Comment by Angery-Stoman** [comment]
furthermore, this is my cargo.toml
<img width="681" alt="image" src="https://github.com/UPB-FILS-MA/questions/assets/163386844/61ca6844-97a4-4e7f-92e4-217474608fef">

**Comment by alexandruradovici** [comment]
Please put here a link to the project repository.

**Comment by Angery-Stoman** [comment]
https://github.com/UPB-FILS-MA/project-Angery-Stoman

**Comment by Angery-Stoman** [comment]
It seems that I have solved the problem with the errors that I was getting. I just had a faulty settings.json and build.rs file.
I will close the issue.
