### ISSUE TITLE
Can't find crate for 'test' error

### ISSUE THREAD

**Issue by 12mihai05** [UPB-FILS-MA/questions#2]
# Can't find crate for 'test' error

I'm encountering the error 'can't find crate for 'test'' in my Rust code from laboratory 2. After researching, I found two potential solutions. One suggests adding 'test = "0.1"' to dependencies in Cargo.toml, while the other suggests modifying settings in `.vscode/settings.json`. like this:
```json
{
  "rust-analyzer.cargo.target": "thumbv7em-none-eabihf",
  "rust-analyzer.checkOnSave.allTargets": false
}
```
After applying the JSON solution, I encountered 271 other problems with missing crates, traits, and macros. Could you advise on how to solve this problem?

![image](https://github.com/UPB-FILS-MA/questions/assets/85041413/654cc85c-8aaa-49d6-860f-51dc88504b71)

![image](https://github.com/UPB-FILS-MA/questions/assets/85041413/e2ea448c-216d-45f5-b9a2-4e2f68a12ea9)

**Comment by irina-b-dev** [comment]
Visual Studio Code might not load all the dependencies.
To check for building issues, please attach the output  `cargo build` command.

1. Check if you have `cargo` install : run `cargo --version`
2. Run `cargo build` in the _**bare_metal**_ directory

**Comment by alexandruradovici** [comment]
The vscode settings seems to be the issue. This is the `settings.json` file from the lab https://github.com/UPB-FILS-MA/lab/blob/main/.vscode/settings.json.

**Comment by 12mihai05** [comment]
It worked after i changed the json file. Thank you.
